Add localStorage as a storage for lists
Reden4005/todolist-react pull request #4
Opened 2021-07-12 13:10 UTC by Reden4005

2021-07-12 19:47 UTC, rsmogura requested changes

2021-07-12 19:47 UTC, rsmogura commented on src/App.jsx
> +            <DashBoard />
Lowercase B

2021-07-12 19:47 UTC, rsmogura commented on src/Dashboard/DashBoard.jsx
> +class DashBoard extends Component {
Lowercase "B"

2021-07-12 19:47 UTC, rsmogura commented on src/Dashboard/DashBoard.jsx
> +    componentDidMount(){
Space after parenthesis

2021-07-12 19:47 UTC, rsmogura commented on src/Dashboard/DashBoard.jsx
> +        return(
Space

2021-07-12 19:47 UTC, rsmogura commented on src/Dashboard/DashBoard.jsx
> +        new ListsStorage(this.state.listTitle);
When the new instance is created and not used?

2021-07-12 19:47 UTC, rsmogura commented on src/Dashboard/DashBoard.jsx
> +            <>
What's this empty tag <>

2021-07-12 19:47 UTC, rsmogura commented on src/Dashboard/DashBoard.jsx
> +        if(this.state.lists) {
Space - please configure linter

2021-07-12 19:47 UTC, rsmogura commented on src/Data/ListsService.js
> +     * Retrieves all lists.
New line after this one

2021-07-12 19:47 UTC, rsmogura commented on src/Data/ListsService.js
> +        const actualLists = JSON.parse(localStorage.getItem("lists"));
Can we de-deuplicate this code "JSON.parse(localStorage.getItem("lists"))" into method loadAllLists?

2021-07-12 19:47 UTC, rsmogura commented on src/Data/ListsService.js
> +    static refreshData() {
Naming. This method is called refereshData, but it actually returns data. "Data" in any way is too generic term.

2021-07-12 19:47 UTC, rsmogura commented on src/Data/ListsService.js
> +        let refreshList = actualLists.map(list => list.tasks);
This variable is called refreshLists, but contains tasks. I think should be renamend

2021-07-12 19:47 UTC, rsmogura commented on src/Data/ListsService.js
> +    static addTasks(listID, taskName) {
Please add few words to method comments.

2021-07-12 19:47 UTC, rsmogura commented on src/Data/ListsStorage.jsx
> +class ListsStorage extends Component {
Is this React component or JavaScript service class. Can we remove Component inheritance and keep it in .js file?

2021-07-12 19:47 UTC, rsmogura commented on src/Data/ListsStorage.jsx
> +    constructor(listName) {
I think this is copy-past from other code, as constructor should be responsible for instatiating the class, not create a new List object and inserting it into storage.

2021-07-12 19:47 UTC, rsmogura commented on src/Data/ListsStorage.jsx
> +    refreshLists(listName) {
Naming. This method does not referesh, please name it in accordance to this what it does.
Please add JS doc comments.
This method looks same ass addNewListToStorage

2021-07-12 19:47 UTC, rsmogura commented on src/Data/ListsStorage.jsx
> +        let choosenList = actualLists.filter(list => list.listName === listName);
I think there are better methods than filter, to find interesting element in array

2021-07-12 19:47 UTC, rsmogura commented on src/Data/ListsStorage.jsx
> +        let actualLists = JSON.parse(localStorage.getItem("lists"));
If actualLists is not going to be changed make it const, it will help better maintain code and modification (i.e. capturing accidental modifications)

2021-07-12 19:47 UTC, rsmogura commented on src/Header/Header.jsx
> +                    className={this.state.isSpinning ? classes.Dots : classes.Dots + " " + classes.DotsWithoutSpinning}></img>
Minor: I wonder if template string can be used to create concatenation of both classes.
Shorter syntax: classes.Dots + '  ' +(isSpinning ? '' : classes.DotsWithout...)

2021-07-12 19:47 UTC, rsmogura commented on src/Header/Header.jsx
> +export default Header;
Please be consistent with other source code about exports, if default or 'named' export is preferred. Personally I think named exports are better because later you can easy add a new export from file.

2021-07-13 07:45 UTC, Reden4005 commented on src/App.jsx
> +            <DashBoard />
done

2021-07-13 07:45 UTC, Reden4005 commented on src/Dashboard/DashBoard.jsx
> +class DashBoard extends Component {
done

2021-07-13 07:46 UTC, Reden4005 commented on src/Dashboard/DashBoard.jsx
> +    componentDidMount(){
done

2021-07-13 07:47 UTC, Reden4005 commented on src/Dashboard/DashBoard.jsx
> +        return(
done

2021-07-13 07:51 UTC, Reden4005 commented on src/Dashboard/DashBoard.jsx
> +        new ListsStorage(this.state.listTitle);
it creates new instance with list's name from event listener.

2021-07-13 07:55 UTC, Reden4005 commented on src/Data/ListsStorage.jsx
> +        let choosenList = actualLists.filter(list => list.listName === listName);
changed for find

2021-07-13 07:57 UTC, Reden4005 commented on src/Data/ListsStorage.jsx
> +        let actualLists = JSON.parse(localStorage.getItem("lists"));
done

2021-07-13 11:53 UTC, Reden4005 commented on src/Header/Header.jsx
> +                    className={this.state.isSpinning ? classes.Dots : classes.Dots + " " + classes.DotsWithoutSpinning}></img>
done

2021-07-13 11:53 UTC, Reden4005 commented on src/Header/Header.jsx
> +export default Header;
done

2021-07-13 12:00 UTC, Reden4005 commented on src/Data/ListsStorage.jsx
> +    refreshLists(listName) {
renamed. There are two different methods, first creates local Storage, second add lists to its.

2021-07-13 19:20 UTC, rsmogura commented on src/App.jsx
> +            <DashBoard />
i don't see it

2021-07-13 19:22 UTC, rsmogura commented on src/Dashboard/DashBoard.jsx
> +        new ListsStorage(this.state.listTitle);
and what happens with this new instance new ListsStorage(this.state.listTitle); if it's not used and logic from constructor is used to do something than this logic should be in method, not constructor.

2021-07-21 07:12 UTC, Reden4005 commented on src/Dashboard/DashBoard.jsx
> +            <>
it is use to cover jsx in one tag, when you don't need any html tag.

2021-07-21 15:37 UTC, rsmogura requested changes

2021-07-21 15:37 UTC, rsmogura commented on src/Data/ListsService.js
> +     * Retrieves all lists.
I meant after text and before return comment

2021-07-21 15:37 UTC, rsmogura commented on src/App.jsx
> +            <Header />
Looks good

2021-07-21 15:37 UTC, rsmogura commented on src/Dashboard/Dashboard.jsx
> +                this.setState({lists});
spaces before lists

2021-07-21 15:37 UTC, rsmogura commented on src/Dashboard/Dashboard.jsx
> +            } else this.setState({});
if main block is in brackets please put else block in brackets too

2021-07-21 15:37 UTC, rsmogura commented on src/Data/ListsStorage.js
> +class ListsStorage {
I think methods from this class should be put into ListService, and list service should be responsible for all operations on lists

2021-07-21 15:37 UTC, rsmogura commented on src/Data/ListsStorage.js
> +    constructor(listName) {
I think using constructors for adding element to storage is wrong idea. Constructor can initialise storage, by reading it and checking if is defined or not, and providing default values (i.e. empty array)

2021-07-21 15:37 UTC, rsmogura commented on src/Data/ListsStorage.js
> +    addStorage(listName) {
I think this method is not needed, and addListToStorage should be used, this methods is insecure as it overrides storage content

2021-07-21 15:37 UTC, rsmogura commented on src/Data/ListsStorage.js
> +                taskId: IdGenerator(),
Can we rename IdGenerator to something like generateId()?

2021-07-21 15:37 UTC, rsmogura commented on src/Data/ListsStorage.js
> +        let choosenList = actualLists.filter(list => list.listId === listId);
Use find instead of filter

2021-07-21 15:37 UTC, rsmogura commented on src/Data/ListsStorage.js
> +        choosenList[0].tasks.push(
There's no guarantee element will be found, element at 0 or found element can be undefined. We should decide what to do, report error to UI, that silently exception, or silently skip.

2021-07-21 15:37 UTC, rsmogura commented on src/Data/ListsStorage.js
> +        const foundListId = actualLists.find(list => list.tasks.find(el => el.taskId === taskIdToRemove)).listId;
This is hard to read, can it be decided into two lines?

2021-07-21 15:37 UTC, rsmogura commented on src/Data/ListsStorage.js
> +        const foundList = actualLists.find(list => list.listId === foundListId);
I think it's not most efficient code, line above you search for list, but take only id. Maybe it will be better to keep found list in const and take id?

2021-07-21 15:37 UTC, rsmogura commented on src/Data/ListsStorage.js
> +        console.log(foundTaskIdxInList, "index");
I think logging looks better if it starts from message not value

2021-07-21 15:37 UTC, rsmogura commented on src/Header/Header.jsx
> +                <h1 className={classes.h1}  >To Do List</h1>
Extra spaces

2021-07-21 15:37 UTC, rsmogura commented on src/ListManager/Lists/List/List.jsx
>          listTitle: "",
Is it still used?

2021-07-21 15:37 UTC, rsmogura commented on src/ListManager/Lists/List/List.jsx
> +            this.storage.addNewTaskToStorage(this.props.name, this.state.task);
Can we use listId here, and read listtname from storage? That's better as list names can be changed concurrently, but ids not

2021-07-21 15:37 UTC, rsmogura commented on src/ListManager/Lists/List/List.jsx
> +            ListsService.addTasks(this.props.name, this.state.task);
Why calling this two methods storage and service?

2021-07-21 15:37 UTC, rsmogura commented on src/ListManager/Lists/List/List.jsx
>          this.mainInput.value = "";
What's mainInput?

2021-07-21 15:37 UTC, rsmogura commented on src/ListManager/Lists/List/List.jsx
>                      deleteList={this.deleteList}/>
What's this.deleteList, I can't find it?

2021-07-21 15:37 UTC, rsmogura commented on src/ListManager/Lists/Tasks/Task/Task.jsx
> +        this.props.delTask(this.props.name);
can we rename delTask to deleteTask?

2021-07-21 15:37 UTC, rsmogura commented on src/ListManager/Lists/Tasks/Tasks.jsx
> +        const foundListId = this.props.list.find(list => list.tasks.find(el => el.taskId === taskToDel)).listId;
This is same comment as before, it's not most efficient. As this method is used in two places, can we put it into service class?

2021-07-21 15:37 UTC, rsmogura commented on src/ListManager/Lists/Tasks/Tasks.jsx
> +            let listWithTasks = this.props.list.find(list => list.listId === this.props.name).tasks;
Rename listWithTasks to tasksInList

2021-07-21 15:37 UTC, rsmogura commented on src/UI/Footer/Footer.jsx
> +            <a className={classes.FooterEnvelope} href="mailto:olus81_81@o2.pl">✉</a>
Remove your private e-mail

2021-07-22 07:48 UTC, Reden4005 commented on src/Dashboard/Dashboard.jsx
> +                this.setState({lists});
?

2021-07-22 07:49 UTC, Reden4005 commented on src/Dashboard/Dashboard.jsx
> +            } else this.setState({});
done

2021-07-22 07:55 UTC, Reden4005 commented on src/Data/ListsStorage.js
> +        console.log(foundTaskIdxInList, "index");
done

2021-07-22 07:57 UTC, Reden4005 commented on src/Header/Header.jsx
> +                <h1 className={classes.h1}  >To Do List</h1>
done

2021-07-22 07:58 UTC, Reden4005 commented on src/ListManager/Lists/List/List.jsx
> +            this.storage.addNewTaskToStorage(this.props.name, this.state.task);
this.props.name is listId

2021-07-22 07:59 UTC, Reden4005 commented on src/ListManager/Lists/List/List.jsx
>          this.mainInput.value = "";
something I must check, it should clear input value after submit.

2021-07-22 08:00 UTC, Reden4005 commented on src/UI/Footer/Footer.jsx
> +            <a className={classes.FooterEnvelope} href="mailto:olus81_81@o2.pl">✉</a>
why?

2021-07-22 10:09 UTC, Reden4005 commented on src/ListManager/Lists/Tasks/Tasks.jsx
> +            let listWithTasks = this.props.list.find(list => list.listId === this.props.name).tasks;
done

2021-07-22 10:11 UTC, Reden4005 commented on src/ListManager/Lists/Tasks/Task/Task.jsx
> +        this.props.delTask(this.props.name);
done

2021-07-22 10:14 UTC, Reden4005 commented on src/ListManager/Lists/List/List.jsx
>                      deleteList={this.deleteList}/>
deleted

2021-07-22 10:25 UTC, Reden4005 commented on src/ListManager/Lists/List/List.jsx
>          this.mainInput.value = "";
changed sumbitListTitleHandler in dashboard and deleted mainInput.

2021-07-22 10:27 UTC, Reden4005 commented on src/Data/ListsStorage.js
> +        const foundListId = actualLists.find(list => list.tasks.find(el => el.taskId === taskIdToRemove)).listId;
done

2021-07-22 10:30 UTC, Reden4005 commented on src/Data/ListsStorage.js
> +        let choosenList = actualLists.filter(list => list.listId === listId);
doesn't work

2021-07-22 10:40 UTC, Reden4005 commented on src/Data/ListsStorage.js
> +                taskId: IdGenerator(),
done

2021-07-26 07:25 UTC, Reden4005 commented on src/Dashboard/DashBoard.jsx
> +        if(this.state.lists) {
done

2021-07-26 07:49 UTC, Reden4005 commented on src/Dashboard/Dashboard.jsx
> +                this.setState({lists});
done

2021-07-26 07:52 UTC, Reden4005 commented on src/ListManager/Lists/List/List.jsx
>          listTitle: "",
yes

2021-07-26 07:52 UTC, Reden4005 commented on src/ListManager/Lists/List/List.jsx
> +            ListsService.addTasks(this.props.name, this.state.task);
deleted

2021-07-26 12:12 UTC, Reden4005 commented on src/Dashboard/DashBoard.jsx
> +        new ListsStorage(this.state.listTitle);
changed

2021-07-26 12:12 UTC, Reden4005 commented on src/Data/ListsService.js
> +    static addTasks(listID, taskName) {
removed

2021-07-26 12:12 UTC, Reden4005 commented on src/Data/ListsStorage.jsx
> +    constructor(listName) {
changed

2021-07-26 12:12 UTC, Reden4005 commented on src/Data/ListsStorage.js
> +    constructor(listName) {
changed

2021-07-26 12:13 UTC, Reden4005 commented on src/Data/ListsStorage.js
> +    addStorage(listName) {
changed

2021-07-26 13:18 UTC, rsmogura requested changes

2021-07-26 13:18 UTC, rsmogura commented on src/Data/ListsStorage.js
> +        if (this.lists === null) {
Where's this.list used, I think not in this method.

2021-07-26 13:18 UTC, rsmogura commented on src/Data/ListsStorage.js
> +        const foundList = actualLists.find(list => list.listId === foundListId);
Still not solved

2021-07-26 13:18 UTC, rsmogura commented on src/Data/ListsStorage.js
> +
Extra new line

2021-07-26 13:18 UTC, rsmogura commented on src/ListManager/Lists/Tasks/Tasks.jsx
> +        const foundListId = this.props.list.find(list => list.tasks.find(el => el.taskId === taskToDel)).listId;
Still not solved

2021-07-27 07:14 UTC, Reden4005 commented on src/Data/ListsStorage.js
> +        if (this.lists === null) {
changed

2021-07-27 13:37 UTC, Reden4005 commented on src/Data/ListsStorage.js
> +        let choosenList = actualLists.filter(list => list.listId === listId);
changed

2021-07-27 13:37 UTC, Reden4005 commented on src/Data/ListsStorage.js
> +        choosenList[0].tasks.push(
changed

2021-07-28 13:35 UTC, rsmogura requested changes

2021-07-28 13:35 UTC, rsmogura commented on src/Data/ListsStorage.js
> +        actualLists.filter(list => list.listId === foundListId)[0].tasks.splice(foundTaskIdxInList, 1);
Find instead of filter

2021-07-29 10:07 UTC, rsmogura requested changes

2021-07-29 10:07 UTC, rsmogura commented on src/Data/ListsStorage.js
> +        let choosenList = actualLists.find(list => list.listId === listId);
const not let

2021-07-29 10:07 UTC, rsmogura commented on src/Data/ListsStorage.js
> +        actualLists.filter(list => list.listId === foundListId)[0].tasks.splice(foundTaskIdxInList, 1);
Not fixed

2021-07-29 11:03 UTC, merged